--- 
title: Routes
---
:sectanchors:
:linkattrs:
:toc: macro
:toclevels: 4

[[tutorial-intro]]
[.tutorial-intro]
== Routes
toc::[]

Routes are one of the fundamental "building blocks" in OpenShift.

A Route is the thing that exposes your Service (and, ultimately, your Pods) to
the outside world. Anyone outside of the OpenShift cluster that wants to access
your application components needs to come in through a Route.

'''

[[setup-instructions]]
=== Setup Instructions
You will need the OpenShift client tool and an account on a system with
OpenShift. Make sure you are logged in to the OpenShift account with the client
tool.

[.steps]
- [.step-number]#1# [.step-title]#Create a Project#
+
[source,bash]
----
oc new-project routes
----

- [.step-number]#2# [.step-title]#Deploy some Pods#
+
There is a link:/code-samples/fundamentals/fundamentals-service-pods.yaml[YAML
file] that defines three pods. It makes use of the `List` type, which is a
special object type that the OpenShift CLI understands. Download the YAML file
and then use `oc` to create the pods:
+
[source,bash]
----
oc create -f fundamentals-service-pods.yaml
----
+
You will see something like:
+
[source,text]
----
pod "hello-openshift-1" created
pod "hello-openshift-2" created
pod "hello-openshift-3" created
----

[.steps]
- [.step-number]#3# [.step-title]#Create a Service#
+
There is a link:/code-samples/fundamentals/fundamentals-service.yaml[YAML
file] that defines the Service above. Go ahead and download it and then use `oc`
to create the Service:
+
[source,bash]
----
oc create -f fundamentals-service.yaml
----
+
You will see something like:
+
[source,text]
----
service "hello-service" created
----

You may wish to wait a few moments before continuing.

[[route-definition]]
=== Route Definition
Routes are closely related to Services in that a Route *exposes* a Service. The
following YAML defines a Route:

[source,yaml]
.route.yaml
----
kind: Route
apiVersion: v1
metadata:
  name: hello-route
  labels:
    name: hello-openshift
spec:
  host: hello-openshift.cloudapps.example.com
  to:
    name: hello-service
  tls:
    termination: edge
----

You can find out more information about Routes in the
link:https://docs.openshift.org/latest/architecture/core_concepts/routes.html[OpenShift
Route Documentation]. For the purpose of our fundamentals, there are only a few
important things in this Route definition:

[cols="2*", options="header"]
|===
|Name
|Description

|`.metadata.name`
|This is the unique identifier ("name") of the Route. Within a
  project, all Route names must be unique.

|`.metadata.labels`
|Various key=value pairs that can be associated with the Route. These may be
used for finding the Route later.

|`.spec.host`
|(Optional) FQDN for the Route. If not present, the default will be used.

|`.spec.to`
|The service exposed by this route
|===

[NOTE]
====
The routing tier in OpenShift will listen for requests for any defined Route
FQDNs and will then proxy the traffic to the appropriate service. You could
define a Route for `www.cnn.com` without error. However, there is no DNS entry
in the "real world" that points `www.cnn.com` at the router in your OpenShift
cluster. Creating a route for `www.cnn.com` will not break the internet. But it
won't get your application working either.
====

'''

[[routing-default-behavior]]
==== Routing Default Behavior
If you do not specify a `host` value, OpenShift will programmatically generate
an FQDN for your Route. The default behavior is to concatenate the Service name
and the Project name. You will see this behavior in action shortly.

'''

[[create-the-route]]
=== Create the Route
A Route definition similar to the one above (lacking a `host` value) can be
downloaded from link:/code-samples/fundamentals/fundamentals-route.yaml[here].
Go ahead and download it and then use `oc` to create the Route:

[source,bash]
----
oc create -f fundamentals-route.yaml
----

You will see something like:
[source,text]
----
route "hello-route" created
----

'''

[[examine-the-route-get]]
=== Examine the Route Using `oc get`

Take a moment to examine the Route you just created.

[source,bash]
----
oc get route
----

You will see something like:

[source,text]
----
NAME          HOST/PORT                                             PATH      SERVICE         TERMINATION   LABELS
hello-route   hello-route-routes.apps.some.domain.com               hello-service   edge          name=hello-openshift
----

Where did the `HOST/PORT` come from? Every OpenShift cluster has a configuration
setting for the default subdomain given to routes. In this case, that subdomain
is `apps.some.domain.com`. The rest of the FQDN for the Route was
programmatically generated by concatenating the unique Route ID and the Project
name.

Since we are in the project `routes` and the Route's ID is `hello-route`, our
full FQDN ends up being `hello-route-routes.apps.some.domain.com`.

[[examine-the-route-describe]]
=== Examine the Route Using `oc describe`

Execute the following:

[source,bash]
----
oc describe route hello-route
----

You will see something like:

[source,text]
----
Name:                   hello-route
Created:                38 seconds ago
Labels:                 name=hello-openshift
Annotations:            openshift.io/host.generated=true
Requested Host:         hello-route-pods.apps.some.domain.com
                          exposed on router router 38 seconds ago
Path:                   <none>
TLS Termination:        edge
Insecure Policy:        <none>
Service:                hello-service
Endpoint Port:          <all endpoint ports>
Endpoints:              10.1.0.10:8080, 10.8.0.10:8080, 10.3.0.10:8080
----

You can see that, just like in the Services tutorial, the Route shares the same
endpoints as the Service. This is because the Route *exposes* the Service.
There's even a command (`oc expose`) that can automatically generate a Route
from a Service, but that is another tutorial.

If you're interested, use `oc describe` to look at the `hello-service` and
validate that the Route's endpoints are the same as the Service's.

'''

[[conclusion]]
[.conclusion]
=== Conclusion
In this tutorial you learned the basics of Routes, one of the fundamental
building blocks of applications in OpenShift.
