--- 
title: Connecting Your Code To a Database
---
:sectanchors:
:linkattrs:
:toc: macro
:toclevels: 4

== Connecting Your Code To a Database
toc::[]

This short document will show you the steps, following best practices, to add a database to your existing code base. We will use PostgreSQL as the main database example. There will be examples of how to connect to the database in each of our major languages. These examples will be very simple and are not neccesarily how you will finally end up connecting. Their purpose is to make sure you understand the concepts so you can apply it to your framework of choice

[NOTE]
====
At the end of this document we will explain why, in general, it is easier to add a database (or message queue, caching layer, etc.) before you add your code. The general idea is that the code containers won't pick up the changes to "services" created after it's creation. To get those changes to be registered you have to restart your code containers. 
====

[[setup-instructions]]
=== Setup Instructions

As mentioned above, we assume you already have a project with code in it. If not, then please go to the documentation XXXXXLINK and create a project. Since project names must be unique, in the examples here we will subsitute <project> for your project. 

You also need to be logged into either the command line utility XXXXXLink or the web console. We will show examples from both.



[[adding-a-db]]
=== Adding A Database

First we need to add a database to the project. While you can do it by adding a Docker image directly using: 

[source,bash]
----
$ oc new-app <dockerhub-namespace>/<db-docker-image>
----

We strongly recommend against it. TODO WHY DO WE RECOMMEND AGAINST IT?

Instead you should use a template that contains not only the configuration for link:/fundamentals/pods.html[the Pod] but also for configuation for link:/fundamentals/services.html[Services], and link:/fundamentals/XXXXXX[Deployment Configurations]. These templates can also be imported into your project or into the entire OpenShift cluster allowing people to re-use the definitions. 

==== Web Console

[.steps]
- [.step-number]#1# [.step-title]#Add to Project#
+
Images need to be here
+
more text


- [.step-number]#2# [.step-title]#Fill in the Form#
+
Test
+
More text

==== CLI instructions
Finding templates in the CLI is a bit more complicated. On OpenShift Online, we have the following DB templates:


